import type { AppProps } from "next/app";
import { Web3Provider, ExternalProvider } from "@ethersproject/providers";
import { Web3ReactProvider } from "@web3-react/core";
import Head from "next/head";
import { InjectedConnector } from "@web3-react/injected-connector";
import { Box, ChakraProvider, HStack } from "@chakra-ui/react";

const getLibrary = (provider: ExternalProvider) => {
  return new Web3Provider(provider);
};

export const injected = new InjectedConnector({
  supportedChainIds: [1, 2, 3, 4, 5, 56, 97, 31337, 11155111],
});


// artical 
//https://betterprogramming.pub/exchanging-encrypted-data-on-blockchain-using-metamask-a2e65a9a896c



export default function App({ Component, pageProps }: AppProps) {
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <ChakraProvider>
        <Head>
          <title>TokenSeal</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <HStack m="20px" spacing={5}>
            <Box as="a" textDecoration="underline" href="/"> With Identities </Box>
            <Box as="a" textDecoration="underline" href="/withWallets"> With Wallet </Box>
        </HStack>


        <Component {...pageProps} />
      </ChakraProvider>
    </Web3ReactProvider>
  );
}
